import os
from flask import Flask, send_from_directory

# Serve the static files from "dist" generated by Vite/React build
app = Flask(__name__, static_folder='dist', static_url_path='/')

@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def serve(path):
    # Check if the requested file exists in the static folder
    if path != "" and os.path.exists(os.path.join(app.static_folder, path)):
        return send_from_directory(app.static_folder, path)
    else:
        # If the file doesn't exist, serve the index.html
        # This allows React Router (if used) to handle the routing
        return send_from_directory(app.static_folder, 'index.html')

if __name__ == '__main__':
    app.run(debug=True, port=5000)
